- kcc/comic2ebook.py
The walk() function does not necessarily return filenames in
alphabetical order. This leads to a random cover image.
Sorting filenames before setting the cover images fixes this issue.
Fixes #127
> Set first image in folder as cover

- kcc/comic2ebook.py
Instead of fixed 1.5 scale ratio, the autoscale feature uses current page's
image width, and dynamically determine the needed scale ratio. The rendering
effects looks okay and speed is fine in my KPW1.
The generated panel view will have two view ports: (top and bottom).
> add autoscale option

- README.md
Installing packages via pip into system folders isn't the happiest solution, as they can end up clashing with the OS package manager. 
Switch to recommending --user flag so the packages install into user's home instead.
Also fixed a typo.
> Do not recommend running pip as root

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comic2panel.py
This pull request consists of several fixes:
**mergeDirectory()**
**Problem:** If the image width is greater than the targetWidth, app skips that image and omits from converting it. 
**Solution:** if that happens the code resizes the image to the targetWidth while preserving the aspect ratio.
**splitImage()**
**Problem:** If the panel at the bottom of the image is not followed by a solid cropped row then the app doesn't add that panel to the panels array. 
**Solution:** If last the panel is detected but there is no solid cropped row at the bottom of the image, code sets the panel bottom dimension to the heightImg.
**Problem:** If the source image is badly cropped and has a thin black outline it causes app to consider whole image as one panel which ends up with lots of unnecessary empty …
> Fixed the skipped/missed images and/or panels

- setup.py
sync python requirements between setup.py and requirements.txt
this avoid installation problem when install from
pip install git+http://
this avoid also problems like these : https://github.com/ciromattia/kcc/issues/410
> sync python requirements between setup.py and requirements.txt

- README.md
* Pillow version requirement in code is 5.2.0+ since support for WebP was added for issue #240 
* Clarify optional GUI dependencies, kcc-c2p.py/kcc-c2e.py does not need pyqt nor raven.
> Clarify Pillow version requirement

- kindlecomicconverter/image.py
- setup.py
- Fix pillow backwards compatibility - sequence of monkey patch is incorrect
- Add mozjpeg-lossless-optimization to setup.py - supporting installation from github via pip
> Fix pillow backwards compatibility, add mozjpeg-lossless-optimization to setup.py

- kindlecomicconverter/comic2ebook.py
Convert process ERROR when using SMB/CIFS : Operation not permitted / link Invalid cross-device link
At the end of convert process, the created file is moved from temp folder to same folder as original file with shutil.move
shutil.move try to change stat (timestamp and file permissions) of the moved file
but like cp/mv shutil.move raise error "Operation not permitted" when copying to a cifs mount
shutil.copy have the same problem when trying to set file permissions. 
**SOLUTION**
use shutil.copyfile then os.remove
shutil.copyfile do not try to preserve timestamp and file permissions
This fix #386
**NOTE**
Here copy stat is not really usefull : it just copy timestamp of the newly created file in temp folder to put the same on the target to correct at best a few seconds
Despîte the fact it …
> use copyfile and delete instead of shutil.move fix #386

- kindlecomicconverter/comic2ebook.py
Rotating the device into landscape mode will cause it to display two
pages side by side. This is particularly useful for input comics whose
spreads are already split into two files.
See https://github.com/kobolabs/epub-spec#synthetic-spreads for
additional information on synthetic spreads.
(Tiny drive-by: Add Kobo format to list of profiles for which the AUTO
format is EPUB)
* Open question: Should we enable this for other Kobo devices?
I hope they would fallback gracefully if they don't fully support the spec, but I've excluded them from this commit since I don't have any to test one.
> Enable Synthetic Spreads for the Kobo Forma.

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
> Added --croppingminimum option to set a cropping minimum area ratio

- README.md
Command Line Tools can be used with pre-built dependencies.
> Document CLI tools debian quick install

- .github/workflows/package-linux.yml
- AppImageBuilder.yml
> new appImage

- kindlecomicconverter/image.py
kcc will crash if source image has transparency and saving to png. 
Was not a problem in mangle due to Python 2/3 differences. https://github.com/python-pillow/Pillow/issues/3150#issuecomment-401577626
Here's a source image that causes crashes.
> remove transparency from image info

- kindlecomicconverter/KCC_gui.py
The instructions in the GUI for downloading the kindle-comic-creator cask utilize an old brew command, so this PR updates the GUI text with the command that Homebrew uses now. It also renames references to "Brew" to "Homebrew".
---
This is what current homebrew tells you if you use the old command that the GUI suggests:
```shell
jameskerrane@Jamess-MBP ~> brew cask install kindle-comic-creator
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
```
This is a successful installation with the command that I changed the GUI instructions to:
```shell
jameskerrane@Jamess-MBP ~ [1]> brew install --cask kindle-comic-creator
==> Downloading https://kc2.s3.amazonaws.com/KindleComicCreatorInstall.dmg
Already downloaded: …
```
> Updates GUI text for new Homebrew version

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
limit kindle scribe image size to (1440, 1920) when using kindlegen
- see #500
- fix  #493
- see  #460
> limit kindle scribe image size to (1440, 1920) when using kindlegen

- README.md
- kindlecomicconverter/KCC_gui.py
@cookie99999 @saisot2006 would this fix 7z support on Windows? I notice that when running from source it finds 7z fine but not when running the `.exe` until added to PATH. 
EDIT: When running from source, it uses the 7z in the `other` folder in the repo, not from PATH.
Would prevent issues like #481
> add 7z to PATH

- kindlecomicconverter/KCC_gui.py
> last version check

- README.md
- kcc-c2e.py
- kcc-c2p.py
- kcc.py
- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comic2panel.py
- kindlecomicconverter/comicarchive.py
OptionParser to ArgumentParser
> OptionParser to ArgumentParser

- environment.yml
As mentioned in #519.
This makes conda setup more effortless for us conda users.
There is a `pyqt` package on **conda-forge** but it was causing conflicts which can be troublesome at times.
I thought it best to stick to **pip** for `pyqt` to avoid conflict resolution.
Tested on **W10**.
Just as a reminder for anyone searching this, the command is
`conda env create -f environment.yml`
> Addition of a conda environment.yml file

- kindlecomicconverter/image.py
Because filling the screen with double page spreads looks amazing on the new Kindle Scribe with its 4:3 aspect ratio. (even though the images are downscaled to 1920x1440 per #460)
Also, replaces previous code that could potentially resize images twice, leading to quality loss, instead just using library functions to do it in one pass.
This also demonstrates the maximum crop visually. **But the real problem is when the edge is only a few pixels wide**  
dx EXAMPLE:
Before:
After:
Here is what the maximum crop looks like:
> Crop images within 3% of device aspect ratio

- environment.yml
Issue: #519 
This PR changes the default Python version when using Anaconda (conda) to 3.11.
This needs a thumbs-up from @darodi before merging.
> Bump conda python to 3.11

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/metadata.py
- requirements.txt
In ComicRack XML Schema, there is a `Title` field that is not being used by KCC. In this PR, I changed so that if this field is set, it will automatically be used.
Also, `pyinstaller` is added to `requirements.txt` for [building on M1](https://github.com/darodi/kcc/issues/4#issuecomment-1364553511) to avoid `pyinstaller: command not found`.
> Override book's title if `Title` is set in XML

- kindlecomicconverter/KCC_gui.py
> change format labels in gui

- README.md
- kindlecomicconverter/KCC_gui.py
How to add 7z to PATH was also way too common of a question on Reddit/GitHub/MobileRead, so added a wiki link instead.
https://github.com/ciromattia/kcc/wiki/Installation#7-zip
May be worth a new release since it's a pretty common question.
> add 7z wiki link

- README.md
KCC website now redirects to GitHub, plus it might confuse people.
Fixes #534
> remove dead download links

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/metadata.py
Previously gave unhelpful error message when using rar on mac:
Now gives proper error.
Also removed all other occurrences of `strerror`
Fixes #528
> Fix unhelpful none error

- README.md
- kindlecomicconverter/KCC_gui.py
refactor display when kindlegen is missing
display_kindlegen_missing
- fixing links
- same display called in 2 contexts
> refactor display when kindlegen is missing

- kindlecomicconverter/KCC_gui.py
Was annoying changing this frequently.
On Kindle Scribe, it will upscale on it's own, so no need to blow up small images. No need to upscale to 1920 in KCC and then let the scribe upscale again to 2480.
Won't matter in most cases since manga is usually 2250. I don't think kindlegen will ever get more than 1920 since there isn't much difference with 2250.
> Default to manga mode and make scribe not upscale 

- kindlecomicconverter/pdfjpgextract.py
> skip single pixel images in PDF

- kcc.py
- kindlecomicconverter/KCC_gui.py
LOCALAPPDATA doesn't actually work until you expand.
Adding Kindle Comic Creator for completeness, even though its from 2014. 
```
C:\Users\*****\AppData\Local\Amazon\KC2>kindlegen
*************************************************************
Amazon kindlegen(Windows) V2.9 build 1029-0897292
A command line e-book compiler
Copyright Amazon.com and its Affiliates 2014
*************************************************************
```
I just tested however, the Windows version of kindlegen included in Kindle Previewer hangs sometimes. Sounds like a wiki page should clarify. I'll update when there is a new release.
Since the version matters, added logic to show location:
> Display kindlegen path

- kindlecomicconverter/comic2ebook.py
Following this issue https://github.com/ciromattia/kcc/issues/392, wrote the same metadata used for double spreads on the kobo for the kindle as well. Worked as intended. Below are screenshots on the KW5. 
Part of the specification for epubs mentioned here https://github.com/kobolabs/epub-spec#synthetic-spreads, so there shouldn't be an issue for any other ereader either if someone wants to make those changes.
> Enable double spread on kindle

- README.md
- kcc.py
- kindlecomicconverter/KCC_gui.py
Since KC2 will ask you to install KP3, I'm sure some user will do that.
This is a potential problem since KP3-kindlegen on windows sometimes hangs, so may as well prioritize the older version from KC2. 
KCC v5.6.3 does not search for KP3 or KC2 on Windows. Will need a new release since we merged in #571  afterward. I think installing KC2 is way simpler than moving `kindlegen.exe` from web archive around.
links here: https://github.com/ciromattia/kcc/wiki/Installation#kindlegen
Fixes #573
> prioritize KC2 over KP3 kindlegen version

- kcc-c2e.py
- kcc-c2p.py
- kcc.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/shared.py
- setup.py
Fixes #588 @DemonEye888
Temporary EXE here: https://github.com/axu2/kcc/actions/runs/6125895319
Please test to confirm it works.
> replace exit() with sys.exit()

- kindlecomicconverter/image.py
I'll have the larger threshold be toggle-able to avoid issues like #585 in a future PR. In that case he had undesirable cropping at 0.043. And at that point may as well make it a 3-way toggle with 0/0.015/0.045.
I just eyeballed the threshold with various images. On my Kindle Scribe, this translates to a 10 pixel border on the sides that get cropped out.
Fixes #585
> lower auto crop threshold from 0.045 to 0.015

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comicarchive.py
Now things are a lot more readable and secure. No shell early quote ends.
Also replaced all uses of `Popen` and `communicate`
May also fix the kindlegen from kp3 error, haven't replicated.
> fix files with ' or " by using arg lists instead of strings

- kindlecomicconverter/comic2ebook.py
- requirements.txt
Fixes #587
Fixes #595
So that's why we did number padding in the old sort method. 
Related: #507 
Prebuilt binaries for download for normal user testing:
Windows EXE: https://github.com/axu2/kcc/actions/runs/6123144358
Mac DMG: https://github.com/axu2/kcc/actions/runs/6123143150
Linux: https://github.com/axu2/kcc/actions/runs/6793159103
> fix page order in pdf and more by using natural sort instead of python sort

- .github/workflows/package-windows-with-docker.yml
I noticed lots of people just download all the files since the GUI version is 3rd in the list. This should make it a little easier. Hopefully reduce the number of people who download the CLI version by accident and cant use.
Also, I'm still open to being added as a collaborator if you need help with issues and releases. It feels bad to leave new bugs in for months.
before:
after:
> make c2e and c2p versions last in file order

- setup.py
Known issue when using QT and pyinstaller: 
https://stackoverflow.com/questions/9469932/app-created-with-pyinstaller-has-a-slow-startup
Using an m2 mac. 17 seconds before rosetta translation and 1 second after rosetta translation.
sample build: https://github.com/axu2/kcc/actions/runs/6938502629
@ronnyhammurabi can you please test this as well? Maybe this was your issue
Use this version with the unsupported archive error merged in: https://github.com/axu2/kcc/actions/runs/6938583635
Onefile doesn't matter since it get packed  into a .app anyways
> Speed up mac startup from 17 seconds to 1 second by not using -F flag

- kindlecomicconverter/comic2ebook.py
Prebuilt binaries for normal user testing:
windows: https://github.com/axu2/kcc/actions/runs/6918518314
mac: https://github.com/axu2/kcc/actions/runs/6918517538
linux: https://github.com/axu2/kcc/actions/runs/6918515994
Skip bookmarks if book is being split into multiple files to avoid list index out of range. functionally equivalent to deleting the comicinfo.xml file.
Fixes #582 
Fixes #586 
Fixes #556 
Fixes #368 
Fixes #352 
Fixes #345 
fixes #229 
fixes #219 
@Tamamaster @DemonEye888 Can you test if this fixes your issue? Works for me with your provided test file.
> fix list index out of range by skipping bookmarks when splitting mobi

- README.md
I find users are still having trouble figuring out how to download and run KCC on Windows from comments on various forums.
I streamlined the readme and moved a lot of linux stuff into the wiki.
Now windows and mac users only need to refer to readme, which comprise 90% of downloads. Since the process is now standardized and not gonna change. https://somsubhra.github.io/github-release-stats/?username=ciromattia&repository=kcc&page=1&per_page=5
I'm not sure where to properly put linux stuff since I don't use linux, feel free to edit my PR with info.
>  streamline downloads and installation readme

- kindlecomicconverter/KCC_gui.py
- Fix #637 
I'm not sure why this causes an issue but it's not really necessary. Nobody else has had a KP3 issue which this check was for. No need to expose usernames in GUI either
https://github.com/axu2/kcc/actions/runs/7131952387
> fix utf-8 error by removing kindlegen location from GUI

- environment.yml
Issue: #641 
This adds missing `natsort` to the list of dependencies in *environment.yml*.
Versioning is kept the same as in *requirements.txt*.
> Added natsort to the dependency list in environment.yml

- kindlecomicconverter/kindle.py
Since Windows can only format non-removable virtual hard drive (VHD) to FAT, which pretends to be a kindle for cover upload purposes. FAT32 is also an option but I don't want to touch the FAT32 related code.
https://github.com/ciromattia/kcc/blob/master/kindlecomicconverter/kindle.py#L33
- Related #508
> add FAT to list of drives for kindle cover generation

- kindlecomicconverter/comic2ebook.py
I was having issue with files in mixed casing, which File Explorer and Finder ignore.
https://natsort.readthedocs.io/en/stable/api.html#natsort.os_sorted
On Windows, it matches Windows File Explorer behavior.
On macOS without pyicu installed, it just does what natsort does while also ignoring extensions and ignoring case. The drawbacks of using it without pyicu seem to not matter in our case. pyicu isn't a simple pip install, so if I don't have to add it that's good.
> use os_sorted natsort with IGNORECASE

- kindlecomicconverter/comicarchive.py
- fix #408 
- fix #630 
It works if we extract the CBZ first and use the folder directly. Therefore, what we are doing in the extract function is probably unnecessary.
> fix access is denied

- kindlecomicconverter/KCC_gui.py
- requirements.txt
The update utility stopped working for me until i changed this.
Was getting this error
```python
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
```
- related #518
> fix update detection by using requests library over urllib

- kindlecomicconverter/comic2ebook.py
Prebuilt binaries for normal user testing (also contains recent error logging changes):
Windows: https://github.com/axu2/kcc/actions/runs/6853834938
Mac: https://github.com/axu2/kcc/actions/runs/6853836566
Linux: https://github.com/axu2/kcc/actions/runs/6853837839
- Fixes #615 
@HamzaM
@vietvu94 
Can you verify if this fixes your issue?
Various characters are illegal in older EPUB readers, including spaces. https://www.w3.org/TR/epub-33/#sec-container-filenames
Code based on: https://stackoverflow.com/questions/12985456/replace-all-non-alphanumeric-characters-in-a-string
Before and after:
I do not have a kobo to test so there's no way for me to verify if this build causes other issues.
> fix kobo file names with .

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comicarchive.py
Not using the slightly unsafe `shell=True` parameter will actually throw a `FileNotFoundError` if I call a command that doesn't exist (like if kindlegen or 7z aren't installed). Called out explicitly here: 
https://docs.python.org/3/library/subprocess.html#exceptions
So prior code in #581 actually crashed when 7z and kindlegen aren't installed during the initial check. Our code prevent selecting MOBI/zip formats afterward, so no further exceptions expected.
So added try: except blocks as needed during initial checks.
>  fix p7zip-rar error and files with ' or " by using arg lists instead of strings

- setup.py
setup.py dependencies don't have "natsort" and "distro", which will break pipx (and possibly pip) installation.
> Fix missing dependencies in setup.py

- kindlecomicconverter/KCC_gui.py
- Fix #652 
Add missing options dictionary parameter to allow search on a different folder for files with the same name.
Reporter confirmed that the behaviour is now working correctly: https://github.com/ciromattia/kcc/issues/652#issuecomment-1874129713
> fix Shift+Click convert button to select output directory renaming

- kindlecomicconverter/KCC_gui.py
This reverts commit 48541404ee2f490417b98d9410036ed623f483ab.
It's just too long in the UI.
> Revert "rename pw to paperwhite"

- kindlecomicconverter/KCC_gui.py
Reset where we save the KCC settings for the first time in over a decade since things have changed a lot. This is a fresh start anyone can jump into if their registry got weird between version differences.
Makes sense to do since we changed gui library. This way old versions won't break after using a new version just in case.
- temporary fix #663 
- related #523
- related #655
> reset saved GUI settings

- kindlecomicconverter/comic2ebook.py
This lets us handle corrupted files gracefully. (Bottom of image is corrupted.)
```
Error during conversion...:
Image file ...page_117.jpg is corrupted. Error: image file is truncated (6 bytes not processed)
Traceback:
File "kindlecomicconverter/KCC_gui.py", line 289, in run
File "kindlecomicconverter/comic2ebook.py", line 1146, in makeBook
File "kindlecomicconverter/comic2ebook.py", line 887, in detectCorruption
```
https://stackoverflow.com/questions/12984426/pil-ioerror-image-file-truncated-with-big-images
> fix Error: image file is truncated

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
If you have a square page, kindlegen will allow a really sharp 1860x1860 image. Much better than prior 1440x1440.
* related #460 
But ideally we could figure out if kindlegen has a hidden arg that doesn't resize...
> Kindle Scribe 1860 max width

- README.md
- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comicarchive.py
tar is an incredibly powerful decompression tool that even supports rar.
It was always been in macOS. And was added to Windows 10 in 2018. It's probably in every linux distro.
https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/
This way, users don't need to install homebrew and xcode on macOS to use it unless they also want metadata editing. Same for Windows.
Also, tar seems faster than 7z!
Test builds: https://github.com/axu2/kcc/releases/tag/v6.0.0-tar
@AlicesReflexion @cookie99999 @darodi Do you think unrar is still needed on fedora?
Related:
- #370 
- #512 
- #515 
- #625 
Feel free to test: @thevenomsnake @shihong5858 @AdrianJesusSilva
> reduce dependency on 7z, unar, homebrew by using builtin tar

- kindlecomicconverter/comic2ebook.py
Kindle Scribe upscales by itself, and the max height of kindlegen is less than the height of the scribe anyways.
- related #460
> don't display upscale warning on kindle scribe

- kcc.py
- fix #721 
@ranart4 
Can you see if this build can be run without putting it in a special place?
https://github.com/axu2/kcc/releases/tag/v6.1.0-user-profile
Can you tell me if kindlegen is at this location? I modified kcc to look there. 
`%UserProfile%\Kindle Previewer 3\lib\fc\bin\`
> search for kindlegen in %UserProfile%

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comicarchive.py
- kindlecomicconverter/shared.py
forgot to handle case where tar fails on corrupted file.
This gives a better error message if extraction fails for some reason, and less duplicated code.
- Fix #730
> fix no such file or directory 7z

- Dockerfile
- Dockerfile-base
- fix #634 
- fix #668
```
ENV PATH="/opt/venv/bin:$PATH"
```
activates the venv
pyside6 has a linux arm64 build, convenient!
> fix Docker linux arm

- kindlecomicconverter/comic2ebook.py
> fix ComicInfo.xml chapters

- README.md
- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
I thought making 
- #762 
was too tedious, this should simplify adding new profiles.
> Make it easier to add new profiles

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/dualmetafix.py
- kindlecomicconverter/kindle.py
- fix #765 
- fix #685 
- fix #508 
- builds off #764
Test builds: 
~~https://github.com/axu2/kcc/releases/tag/v6.2.1-pdoc~~
~~https://github.com/axu2/kcc/releases/tag/v6.2.1-comicrack-pdoc~~
https://github.com/axu2/kcc/releases/tag/v6.3.0
The Kindle Colorsoft has been reported to not expose the system/thumbnails folder for covers, so here's a workaround and pre-built exe.
It just replaces EBOK tag with PDOC, so Kindle reads the cover directly from the file. Please test and tell me if it has issues.
Also, should I remove the ASIN tag?
And does anyone remember when pdoc covers started being read by Kindles? @Zappy86
> simplify cover upload on newer MTP based Kindles by replacing EBOK with PDOC

- kindlecomicconverter/comic2ebook.py
- fix #742 
Please test @bust4cap
> fix bookmark drift when dedupecover is checked

- kindlecomicconverter/comicarchive.py
Bazzite is Fedora-based but fails the `distro.id() == 'fedora'` check because `distro.id()` resolves to "bazzite." I added an additional check to include `distro.like() == 'fedora'` for situations like this.
This needs to be formatted as an or statement because plain Fedora resolves `distro.like()` as a null string.
> Add additional check for differently named Fedora-based distros

- kcc.py
@termdisc 
Can you test, I don't have any linux. This is slightly modified macos code, so unsure if it modifies linux behavior in an unexpected way.
I also just added all the macos locations as well.
This PR is because /usr/local/bin is read only on steam deck. @darodi
> linux search for kindlegen in ~/.local/bin for steam deck and more

- kcc-c2e.py
- kcc-c2p.py
- kcc.py
> modify path with c2e and c2p too for kindlegen/7z

- .github/workflows/package-linux.yml
Reverts ciromattia/kcc#795
- fix #796
> Revert "build appimage on ubuntu-20.04 instead of 22.04"

- environment.yml
- requirements.txt
- setup.py
fastnumbers is tricky to install on some platforms. @catsout 
And our size of ~200 strings to sort per file means this makes no difference in sorting time, sorting time is insignificant for kcc.
> remove fastnumbers

- gui/KCC.ui
- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/KCC_ui.py
> add author gui

- .github/workflows/package-linux.yml
Even though GitHub says `ubuntu-latest` currently refers to `ubuntu-22.04`, the build logs actually showed that it was building on `24.04` in some cases. This is probably why it wasn't running properly on older platforms.
So I will explicitly require 22.04. I tried 20.04 earlier and that caused segmentation fault issues that I don't really want to look into.
@jeffmcneill Please test the rebuild of 7.1.2 soon.
> build appimage on ubuntu-22.04 instead of 24.04

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
@utopiafallen This was very useful when debugging an issue related to large files. Even with a very fast CPU (Apple M2), this sped things up a lot.
The progress bar updates have strange behavior on macOS however, I don't think I can merge those. Basically, on macOS, it doesn't show the format text ever.
I can confirm caller catches corrupt images appropriately.
> improve speed by reverting corrupt image detection refactor

- kindlecomicconverter/comic2ebook.py
Optimize getWorkFolder() to use directory renaming instead of copy + …
…delete
Way cheaper to just rename a directory into the destination than to copy and delete.
@utopiafallen Thanks again. I removed the perf_counters since it's no longer neccessary.
> improve speed by using renames instead of copytree+rmtree

- kindlecomicconverter/comicarchive.py
`tar` actually can leave files in a weird state. So I'll make it the last priority.
> fix cannot identify image file by deprioritizng tar

- kindlecomicconverter/KCC_gui.py
Partially revert 
- https://github.com/ciromattia/kcc/commit/30b8770e34926f3d5ee6e55d36abbb1d5b1e354c
Was causing vague error messages like:
```
2
```
Instead of like:
```
[Errno 2] No such file or directory: 'blahblahblah'
```
> fix error messages that only say a single number

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/shared.py
@utopiafallen Thanks, I saw about a 5x speedup on macOS. I changed your `subprocess.run` to make it multiplatform and made 7z a preference but falling back to older method if 7z not available.
> Speed up zip file creation by using 7z
> - 7z is about 10x faster than whatever the Python ZipFile library was doing, probably because compression is multithreaded by default in 7z, so makeZip() now just calls through to 7z.
> Use 7z to save ~10 sec per epub/cbz compression over Python ZipFile

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
@Lukas-Holecy This should also fix your memory issues. Instead of metadata dicts, store the metadata in the filename. this matters because image processing is parallelized.
- fix https://github.com/ciromattia/kcc/issues/850#issuecomment-2706339742
> memory optimization: store metadata in filenames, not a global dict

- .github/workflows/package-windows-with-docker.yml
testing now that we are signed which process gives less AV flags.
Also, this lets things be more parallel since building 3 exe sequentially is SLOW.
> revert build windows gui with docker

- kindlecomicconverter/image.py
- related #856 
since cover is duplicated, you see the split version in library view.
> split covers in half if too wide

- gui/KCC.ui
- kindlecomicconverter/KCC_ui.py
Needs to be more obvious blurring is occuring.
> rename reduce rainbow to rainbow blur

- kindlecomicconverter/comic2ebook.py
@neyney10 This looks fine? I noticed the `maybeCrop` function was being called twice per image, this shaves a second per volume for me.
> speed optimization: fix accidentally cropping pages twice

- kindlecomicconverter/comic2panel.py
I found that in the comic2panel.py file there is the following line: newPage.save(os.path.join(path, os.path.splitext(name)[0] + '-' + str(pageNumber) + '.png'), 'PNG') which causes that, if the name of the webton is not divided correctly, it uses the numbering 1,2,...,10 and that causes errors in some ereaders, if it is changed to: newPage.save(os.path.join(path, os.path.splitext(name)[0] + '-' + str(pageNumber).zfill(4) + '.png'), 'PNG') now it uses the numbering 0001,0001,...,0010 which does not cause those errors
> fix webtoon page numbers 

- kindlecomicconverter/KCC_gui.py
- fix #414 
If you truly want HQ panel view use Kindle Scribe profile.
If you want to cut pages in half, use landscape mode.
> disable old panel view method for new kindles

- setup.py
Somehow still getting virus warnings, maybe this will fix.
> add pyinstaller --clean and rename Windows build from KCC to Kindle Comic Converter

- kindlecomicconverter/image.py
@mergen3107 @KaMyKaSii
- related https://github.com/koreader/koreader/issues/9163#issuecomment-1146637205
Do you think this change would help koreader users?
Previously, if you used an (~800x1200) image smaller than the device (1860x2480), and **upscale is unchecked** in cbz output mode, it would add huge margins.
This code change disables the added padding and outputs the image at it's original resoltion. Since KCC doesn't upscale to the huge resolution, this should mean much smaller filesizes at the same quality compared to using the upscale option.
test builds here:
https://github.com/axu2/kcc/releases/tag/v7.4.1-mapaki-koreader
> CBZ output: Don't add padding around images when upscale unchecked or when white background is checked

- requirements.txt
@neyney10 
As of Numpy 2.3, all the compatibility issues I had before seem to be gone, so I'm no longer requiring numpy 1.
Numpy 1 is a pain to install on newer Python versions.
> Just updated this and added numpy to depends; sorry for missing that!
> So, I've added a dependency on python-numpy, which is numpy 2, but upstream kcc depends on numpy 1. This could be provided with python-numpy1 (on the AUR), but that would conflict with python-numpy, and could cause issues with other packages. Apparently upstream didn't test with numpy 2 (https://github.com/ciromattia/kcc/pull/778), and I ran some tests and it seems to work fine with numpy 2, so I decided to just use that one.
>If you guys find any issue with this, please let me know and I'll switch to python-numpy1. …
> upgrade to numpy 2

- kindlecomicconverter/comic2ebook.py
@JuanPardos this fixes the 
> However something weird happened. Note not all pages looks the same, don't know if this is the special rendering in action but it looks like 1 image on top left, two if there is enough space for second. In pages with only 1 image there is wide right and bottom margin, the first image starts at top left always.
> fix scribe skinny images

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
Fixes bit depth/quantization for grayscale pages with forcepng + forcecolor options.
Now color pages will be saved in 8bit truecolor (24bit per pixel) and grayscale pages in 8bit (2bit/4bit/8bit dynamically based on given quantization palette after https://github.com/ciromattia/kcc/pull/976 is merged)
Closes https://github.com/ciromattia/kcc/issues/932
Slight optimization to JPEG grayscale pages with forcecolor option.
Consistently results in ~0.7% reduction in output file size.
> Fixes to grayscale pages in forcecolor mode

- kindlecomicconverter/comic2ebook.py
- #972 
apparently this change broke the mupdf renderer for epubs, not sure how many people actually use that though. So I'll only add it when needed.
@9783e6
> only add display-block for kindle scribe

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/image.py
Improves the color detection algorithm to better handle images that contain only small regions of color but have a low overall color-to-pixel ratio. Previously, such images were often misclassified as grayscale, even when they did contain color. With this change, these pages are now correctly identified as color, reducing false negatives in color detection.
Additionally, this PR makes the color check run only when it’s actually needed, instead of running it up front every time. This avoids doing extra work if the color check isn’t used, which reduces unnecessary computation.
- Closes https://github.com/ciromattia/kcc/issues/995
> Improved color detection

- kindlecomicconverter/image.py
- kindlecomicconverter/rainbow_artifacts_eraser.py
Highly effective removal of rainbow effect artifacts on Kaleido 3 displays by significantly attenuating the responsible frequencies in the spectral domain (>= 0.3 cycles/pixel, oriented around 135°).
This method avoids blurring the entire image by precisely targeting problematic frequencies (at the cost of a ~ 18% processing time increase vs the blurring method on processed images).
Fixes #771
> Remove the rainbow effect on kaleido 3 by precisely attenuating the frequencies responsible instead of blurring the image

- kindlecomicconverter/comic2ebook.py
- #983 
This is way faster since the recipe requires it.
https://pymupdf.readthedocs.io/en/latest/recipes-multiprocessing.html
> pdf input uses all cpu cores

- kindlecomicconverter/rainbow_artifacts_eraser.py
Rainbow erase: add param s=luminance.shape to irfft2 to avoid dimensions error on luminance
Fixes #1037
> Fix #1037: Rainbow eraser error on odd widths

- kindlecomicconverter/rainbow_artifacts_eraser.py
Enable odd width for BW image when using Rainbow Eraser by passing original image dimensions to irfft2
See #1037
> Enable odd width for BW image when using Rainbow Eraser by passing original image dimensions to irfft2

- kindlecomicconverter/comic2ebook.py
> only remove super long subfolder names on Windows

- kindlecomicconverter/KCC_gui.py
- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comic2panel.py
- kindlecomicconverter/metadata.py
@Silver0006 @Constantin1489 
Just FYI, `rmtree(path, True)` is called with the `True` argument in every single other place in the codebase, this ignores errors.
Some platforms like `macos-11` will have strange errors if not called with `True`. If rmtree fails you shouldn't fail the conversion.
- https://github.com/ciromattia/kcc/issues/891#issuecomment-3146130420
> fix rmtree Directory not empty: 'Images'

- kindlecomicconverter/image.py
Don't apply rainbow eraser on images with 1px dimensions
fix #1056
> Prevents rainbow eraser crash on images with 1px dimensions

- kindlecomicconverter/image.py
@9783e6 Just FYI
Had pairs of thresholds like this where bw images were falsely flagged as color.
```
37    28
37    29
38    32
38    33
38    33
39    27
39    27
39    35
39    35
40    33
40    33
41    32
41    32
56    113
73    176
83    114
89    124
92    163
103    87
103    176
107    142
107    163
108    182
110    85
110    87
115    122
132    144
```
A threshold of 50 meant no false positives.
> Color detection has fewer false postives

- kindlecomicconverter/comic2ebook.py
- kindlecomicconverter/comicarchive.py
Linux (and probably macOS) filesystems allow for folders with special characters in it.  This appears to cause issues when a folder that contains a question mark is passed to 7zip within the makeZIP function.  Since ? is considered a wildcard character, 7zip ends up adding additional folders to the zip file, which results in an epub with incorrect structure.
To solve this, we can pass `cwd=basedir` within subprocess_run so that 7zip is executed within basedir, and have 7zip archive everything within that folder.
This should 
- fix #1085
> Fix makeZIP function to allow for special characters in folder names
